### ISSUE TITLE
后期会有打算编写为独立的lib库嘛

### ISSUE THREAD

**Issue by mocha666** [CarmJos/MineRedis#2]
### **功能简述**
后期会有打算编写为独立的lib库嘛

### **需求来源**
可以像EasySQL一样整合到Jar包中使用，不仅仅可以使用到mc当中，也可以使用到其他程序中，之前使用EasySql可以整合到spring中，实现网页端和mc服务器端整合一样的代码

**Comment by CarmJos** [comment]
您好！本库实际为 lettuce 的MineCraft插件版封装。如果您需要独立使用，可以直接依赖调用 Lettuce 库使用。

**Comment by mocha666** [comment]
感谢大佬指点
